### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dineshrajdhanapathyDD**
update the file error.

### CODE REVIEW

**Comment by ntheanh201** [comment]
thanks for the 1st pull request, but it'll not work if you remove the quote ' out of the password, because that password contains special character (!)

**Comment by dineshrajdhanapathyDD** [comment]
Thanks for your valuable reply. just have gone through documentation that mentions two passwords placed as quotes including Nautilus DB Server and Jenkins Server for CI/CD. another password does not mention password quotes that's why.

**Comment by ntheanh201** [comment]
Yeah I did it for people can just copy it into the terminal and it'll work

**Comment by dineshrajdhanapathyDD** [comment]
Happy to hear this... that's why contributed to this journey bro.

**Pull request closed without merging**
